"""Generates the app icon: an amber star on the app's purple.

Writes the iOS AppIcon set and the Android launcher icons (legacy PNGs and
an adaptive icon with a monochrome layer for themed icons).

Usage: python3 tool/generate_app_icon.py   (needs Pillow: pip install pillow)
"""

import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent

# Colors.deepPurple (the app's seed color) shades, and the star's amber.
TOP = (0x7E, 0x57, 0xC2)  # deepPurple 400
BOTTOM = (0x51, 0x2D, 0xA8)  # deepPurple 700
STAR = (0xFF, 0xC1, 0x07)  # amber
ADAPTIVE_BACKGROUND = "#673AB7"  # deepPurple 500

# Drawn large, then scaled down, for smooth edges.
CANVAS = 2048


def star_points(center, outer, inner, rotation=-math.pi / 2):
    """The ten corners of a five-pointed star."""
    cx, cy = center
    points = []
    for i in range(10):
        radius = outer if i % 2 == 0 else inner
        angle = rotation + i * math.pi / 5
        points.append((cx + radius * math.cos(angle), cy + radius * math.sin(angle)))
    return points


def draw_star(image, scale, color):
    """Draws a star with rounded corners, [scale] of the image wide."""
    size = image.width
    outer = size * scale / 2
    # Lower the star slightly so it looks centered (its points are uneven).
    center = (size / 2, size / 2 + outer * 0.08)
    points = star_points(center, outer, outer * 0.48)
    draw = ImageDraw.Draw(image)
    rounding = max(1, int(outer * 0.12))
    draw.polygon(points, fill=color)
    # A thick outline with round joins rounds the corners.
    # Ends on the second corner too, so the first corner also gets a joint.
    draw.line(points + points[:2], fill=color, width=rounding, joint="curve")


def gradient(size):
    image = Image.new("RGB", (size, size))
    draw = ImageDraw.Draw(image)
    for y in range(size):
        t = y / (size - 1)
        color = tuple(round(a + (b - a) * t) for a, b in zip(TOP, BOTTOM))
        draw.line([(0, y), (size, y)], fill=color)
    return image


def full_icon():
    """The square icon: iOS rounds its corners itself."""
    image = gradient(CANVAS)
    draw_star(image, 0.62, STAR)
    return image


def rounded(image, radius_fraction=0.22):
    """[image] with rounded corners, for Android's legacy icons."""
    mask = Image.new("L", image.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, image.width - 1, image.height - 1],
        radius=image.width * radius_fraction,
        fill=255,
    )
    result = Image.new("RGBA", image.size, (0, 0, 0, 0))
    result.paste(image, mask=mask)
    return result


def foreground(color):
    """An adaptive icon layer: the star within the 66 of 108 dp safe zone."""
    image = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    draw_star(image, 0.85 * 66 / 108, color)
    return image


def save(image, path, size):
    path.parent.mkdir(parents=True, exist_ok=True)
    image.resize((size, size), Image.LANCZOS).save(path)


def ios():
    icon = full_icon()
    folder = ROOT / "ios/Runner/Assets.xcassets/AppIcon.appiconset"
    for name, points, scale in [
        ("20x20@1x", 20, 1), ("20x20@2x", 20, 2), ("20x20@3x", 20, 3),
        ("29x29@1x", 29, 1), ("29x29@2x", 29, 2), ("29x29@3x", 29, 3),
        ("40x40@1x", 40, 1), ("40x40@2x", 40, 2), ("40x40@3x", 40, 3),
        ("60x60@2x", 60, 2), ("60x60@3x", 60, 3),
        ("76x76@1x", 76, 1), ("76x76@2x", 76, 2),
        ("83.5x83.5@2x", 83.5, 2),
        ("1024x1024@1x", 1024, 1),
    ]:
        # App Store icons must not have an alpha channel.
        save(icon.convert("RGB"), folder / f"Icon-App-{name}.png", round(points * scale))


def android():
    res = ROOT / "android/app/src/main/res"
    legacy = rounded(full_icon())
    star = foreground(STAR)
    monochrome = foreground((255, 255, 255))
    for density, scale in [
        ("mdpi", 1), ("hdpi", 1.5), ("xhdpi", 2), ("xxhdpi", 3), ("xxxhdpi", 4)
    ]:
        save(legacy, res / f"mipmap-{density}/ic_launcher.png", round(48 * scale))
        save(star, res / f"mipmap-{density}/ic_launcher_foreground.png", round(108 * scale))
        save(monochrome, res / f"mipmap-{density}/ic_launcher_monochrome.png", round(108 * scale))

    (res / "mipmap-anydpi-v26").mkdir(parents=True, exist_ok=True)
    (res / "mipmap-anydpi-v26/ic_launcher.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/generate_app_icon.py -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />\n'
        "</adaptive-icon>\n"
    )
    (res / "values/ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/generate_app_icon.py -->\n'
        "<resources>\n"
        f'    <color name="ic_launcher_background">{ADAPTIVE_BACKGROUND}</color>\n'
        "</resources>\n"
    )


if __name__ == "__main__":
    ios()
    android()
    print("Generated the iOS and Android app icons.")
