#!/bin/sh
# Validate that a commit message follows Conventional Commits.
# Usage: scripts/check-commit-msg.sh <commit-msg-file>

subject=$(head -n 1 "$1")

# Messages generated by git itself.
case "$subject" in
  Merge\ * | Revert\ * | fixup!\ * | squash!\ * | amend!\ *) exit 0 ;;
esac

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?!?: [^ ].*$'

if ! printf '%s\n' "$subject" | grep -Eq "$pattern"; then
  echo "commit-msg: subject does not follow Conventional Commits:" >&2
  echo "  $subject" >&2
  echo "Expected: <type>(<optional scope>): <summary>, e.g. 'feat(ui): add search page'." >&2
  echo "See AGENTS.md for the allowed types." >&2
  exit 1
fi

if [ "${#subject}" -gt 72 ]; then
  echo "commit-msg: subject is ${#subject} characters; keep it at 72 or fewer." >&2
  exit 1
fi
